Repository capitalone/DataProfiler, pull requests merged in 2021-03, with the labels that each got.

#43 Update documentation for extending / changing labels of the data labeler
  README.md
Labels: Documentation

#41 Profiler runs without TF & TF only executes when necessary
  .gitignore
  dataprofiler/__init__.py
  dataprofiler/labelers/__init__.py
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/labelers/data_labelers.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/test_data_profiler.py
Labels: Medium Priority, Refactor

#45 Seperate labeler as an extra
  .github/workflows/test-python-package.yml
  README.md
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/version.py
  requirements-ml.txt
  requirements.txt
  setup.py
Labels: Low Priority, New Feature

#48 refactor label extension for data labeler
  README.md
  dataprofiler/data_readers/csv_data.py
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/tests/labelers/test_base_model.py
  dataprofiler/tests/labelers/test_character_level_cnn_model.py
  dataprofiler/tests/labelers/test_data_labelers.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/labelers/test_regex_model.py
  dataprofiler/tests/labelers/test_unstructured_data_labeler.py
Labels: Bug, Refactor

#56 Added ability to likely identify all string delimited (CSV) data
  README.md
  dataprofiler/data_readers/csv_data.py
  dataprofiler/tests/data/csv/all-strings-skip-header-author.csv
  dataprofiler/tests/data/csv/all-strings-skip-header.csv
  dataprofiler/tests/data/csv/all-strings-skip-partial-header.csv
  dataprofiler/tests/data/csv/all-strings-standard-header-data-quotes.csv
  dataprofiler/tests/data/csv/all-strings-standard-header-quotes.csv
  dataprofiler/tests/data/csv/all-strings-standard-header.csv
  dataprofiler/tests/data/csv/small-num-negative.csv
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: Bug, Medium Priority

#51 Add Tests For BooleanOption and BaseColumnOptions Classes
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/abstract_test_options.py
  dataprofiler/tests/profilers/test_base_column_options.py
  dataprofiler/tests/profilers/test_base_option.py
  dataprofiler/tests/profilers/test_boolean_option.py
Labels: Low Priority

#60 add header test and fix to allow user to set even if 0
  README.md
  dataprofiler/data_readers/csv_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: Refactor

#70 Update unique row detection method, reduce processing time by >91%
  dataprofiler/profilers/profile_builder.py
Labels: Bug, High Priority

#74 Fixes option tests in case done in parallel
  dataprofiler/tests/profilers/abstract_test_options.py
  dataprofiler/tests/profilers/test_base_column_options.py
  dataprofiler/tests/profilers/test_base_option.py
  dataprofiler/tests/profilers/test_boolean_option.py
Labels: Bug

#75 Improve delimiter detection
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/tests/data/csv/daily-activity-sheet-@-singlequote.csv
  dataprofiler/tests/data/csv/daily-activity-sheet-@.csv
  dataprofiler/tests/data/csv/daily-activity-sheet-tab.csv
  dataprofiler/tests/data/csv/num-negative-title-large.csv
  dataprofiler/tests/data/csv/num-negative-title.csv
  dataprofiler/tests/data/csv/preferred-check-small-num.csv
  dataprofiler/tests/data/csv/quote-test-singlequote.txt
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/data_readers/test_text_data.py
Labels: Bug, Medium Priority

#83 Fix reloading single quotes
  dataprofiler/data_readers/csv_data.py
  dataprofiler/tests/data/csv/daily-activity-sheet-int-description.csv
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: Bug, Low Priority

#88 Streamline null counting of regex (20% faster)
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Medium Priority, Refactor

#85 Shallow copy where possible in data processing (15% faster)
  dataprofiler/labelers/data_processing.py
Labels: Medium Priority, Refactor

#86 Remove 'tolist()' calls in model (predictions & confidences) (25% faster)
  dataprofiler/labelers/character_level_cnn_model.py
Labels: Medium Priority, Refactor

#55 Update _check_and_return_valid_data_format and preprocessors to operate on np arrays
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_character_level_cnn_model.py
  dataprofiler/tests/labelers/test_data_labelers.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/labelers/test_integration_unstructured_data_labeler.py
  dataprofiler/tests/labelers/test_unstructured_data_labeler.py
Labels: Bug, Low Priority

#93 Added Warnings when sample size doesnt match dataset size
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, Medium Priority, Refactor

#90 Add progress bar for profiler
  dataprofiler/profilers/profile_builder.py
Labels: Low Priority, New Feature

#89 Validate Options for CSVData
  dataprofiler/data_readers/csv_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: Medium Priority, New Feature

#81 Update precision calculation to address scientific notation, ints, and spaces
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/tests/profilers/test_float_column_profile.py
Labels: Bug, Refactor

#96 Constrain memory for CSVData Match / Header check
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/tests/data/csv/empty.csv
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/data_readers/test_data_utils.py
  dataprofiler/tests/data_readers/test_text_data.py
Labels: Medium Priority, Refactor

#82 Fix issue of loading data labeler multiple times (50% faster)
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/profilers/test_profiler_options.py
Labels: High Priority, Refactor, Work In Progress

#98 Fix data labeler set bug
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/test_profiler_options.py
Labels: Bug, Medium Priority

#99 0.4.0 update version for release
  dataprofiler/version.py
Labels: Documentation

#100 Fix to ensure ML isn't necessary
  .github/workflows/test-python-package.yml
  dataprofiler/profilers/profile_builder.py
  dataprofiler/version.py
Labels: Bug, High Priority

#102 added requirement for tqdm with the ml components
  requirements-ml.txt
Labels: Low Priority

#101 Fixed the Null Count Bug
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/data/csv/empty_rows.txt
  dataprofiler/tests/data/csv/iris-with-null-rows.csv
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority, New Feature

#106 Improved chunking index speeds
  .github/workflows/test-python-package.yml
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Medium Priority, Refactor

#108 rename label BACKGROUND -> UNKNOWN
  README.md
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/labelers/labeler_utils.py
  dataprofiler/labelers/regex_model.py
  dataprofiler/profilers/unstructured_data_labeler_column_profile.py
  dataprofiler/tests/labelers/test_character_level_cnn_model.py
  dataprofiler/tests/labelers/test_classification_report_utils.py
  dataprofiler/tests/labelers/test_data_labelers.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/labelers/test_integration_unstructured_data_labeler.py
  dataprofiler/tests/labelers/test_labeler_utils.py
  dataprofiler/tests/labelers/test_regex_model.py
  dataprofiler/tests/labelers/test_unstructured_data_labeler.py
  dataprofiler/tests/profilers/test_unstructured_data_labeler_column_profile.py
  resources/labelers/regex_model/label_mapping.json
  resources/labelers/regex_model/model_parameters.json
  resources/labelers/structured_model/label_mapping.json
  resources/labelers/structured_model/model_parameters.json
  resources/labelers/structured_model/postprocessor_parameters.json
  resources/labelers/structured_model/preprocessor_parameters.json
  resources/labelers/unstructured_model/label_mapping.json
  resources/labelers/unstructured_model/model_parameters.json
  resources/labelers/unstructured_model/postprocessor_parameters.json
  resources/labelers/unstructured_model/preprocessor_parameters.json
Labels: Low Priority, Refactor

#110 Removing unnecessary keys in reports
  README.md
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/helpers/test_report_helpers.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/test_text_column_profile.py
  dataprofiler/version.py
  requirements-ml.txt
Labels: Bug, Low Priority, Refactor

#117 Fixed the null count and total samples, and more.
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#116 examples for data labeler
  examples/data_labeler_predict_train.ipynb
Labels: Documentation, Low Priority

#118 fix bug related to single key when generating a report
  README.md
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, Medium Priority
