Repository capitalone/DataProfiler, pull requests merged in 2021-02, with the labels that each got.

#4 Update structured processor flatten separators
  resources/labelers/structured_model/postprocessor_parameters.json
  resources/labelers/structured_model/preprocessor_parameters.json
Labels: Medium Priority, Refactor

#5 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/open_issue.md
Labels: Documentation, Medium Priority

#10 updated the setup, readme and actions to push to pypi on release
  .github/workflows/publish-python-package.yml
  README.md
  setup.py
Labels: Documentation, Medium Priority

#13 ensure CharacterLevelCnnModel properly referenced in encoding / loading for model in TF
  data_profiler/labelers/character_level_cnn_model.py
Labels: Bug, Medium Priority

#18 Updated .gitignore, update README to use DataProfiler, add Loading Data example
  .gitignore
  README.md
  doc/DATA_LOADING.md
Labels: Documentation, Medium Priority

#24 Update Tests to Enable New Models
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/labelers/test_integration_unstructured_data_labeler.py
  dataprofiler/tests/profilers/test_unstructured_data_labeler_column_profile.py
Labels: Low Priority, Refactor
