Repository capitalone/DataProfiler, pull requests merged in 2021-08, with the labels that each got.

#367 Graphs: Create function which accepts a profiler and creates histogram bar charts
  .github/workflows/publish-python-package.yml
  .github/workflows/test-python-package.yml
  dataprofiler/reports/__init__.py
  dataprofiler/reports/graphs.py
  dataprofiler/tests/reports/__init__.py
  dataprofiler/tests/reports/test_graphs.py
  requirements-reports.txt
  setup.py
Labels: Medium Priority, New Feature

#368 Logger implementation in profile_builder
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/test_dp_logging.py
Labels: Medium Priority, New Feature

#378 Allow text to determine encoding automatically
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/base_data.py
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/data_readers/parquet_data.py
  dataprofiler/data_readers/text_data.py
  dataprofiler/tests/data/txt/utf16.txt
  dataprofiler/tests/data/txt/utf8.txt
  dataprofiler/tests/data_readers/test_avro_data.py
  dataprofiler/tests/data_readers/test_base_data.py
  dataprofiler/tests/data_readers/test_filepath_or_buffer.py
  dataprofiler/tests/data_readers/test_json_data.py
  dataprofiler/tests/data_readers/test_parquet_data.py
  dataprofiler/tests/data_readers/test_text_data.py
Labels: Medium Priority, Refactor

#383 Fixes bug in _get_quantiles when median case occurs
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
Labels: Bug, High Priority

#384 Catch Divide by 0 bug for unique row ratio
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#382 Add mode to numeric stats
  README.md
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: High Priority, New Feature

#385 Make clean data function static again due to multiprocessing and model issue
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#379 Github pages for graphs
  docs/source/dataprofiler.reports.graphs.rst
  docs/source/dataprofiler.reports.rst
  docs/source/graphs.rst
Labels: Documentation, Low Priority

#386 Version update to 0.7.1
  dataprofiler/version.py
Labels: Bug, Documentation, High Priority

#391 Updates to codeowners / gitignore
  .gitignore
  CODEOWNERS
Labels: Documentation

#394 Add chi2 matrix to readme
  README.md
Labels: Documentation, Medium Priority

#376 Add median absolute deviation
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: High Priority, New Feature

#399 gh-pages: add chi2 differences
  docs/source/profiler.rst
Labels: Documentation, Medium Priority

#398 Chi squared Homogenity differences
  dataprofiler/data_readers/csv_data.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#401 doc: Add profile differences to the readme documentation
  README.md
Labels: Documentation, Medium Priority
