Repository capitalone/DataProfiler, pull requests merged in 2021-07, with the labels that each got.

#291 StructuredProfiler _profile dict -> list refactor (part 1/3)
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor

#292 Added context manager
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/filepath_or_buffer.py
  dataprofiler/tests/data_readers/test_filepath_or_buffer.py
Labels: High Priority, Refactor

#281 Add correlation update feature to DP
  README.md
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/utils.py
Labels: High Priority, New Feature

#303 StructuredProfiler report dict -> list refactor (part 2/3)
  .github/workflows/test-python-package.yml
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor

#312 Update README and example notebooks with new Structured profile list paradigm (part 3/3)
  .github/workflows/test-python-package.yml
  README.md
  examples/add_new_model_to_data_labeler.ipynb
  examples/labeler.ipynb
  examples/structured_profilers.ipynb
  examples/unstructured_profilers.ipynb
Labels: Documentation

#313 Bug fix to make sure samples being stored by UnstructuredProfiler save
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#315 Allow StructuredProfiler to be able to support duplicate columns
  README.md
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/utils.py
  examples/add_new_model_to_data_labeler.ipynb
  examples/labeler.ipynb
  examples/structured_profilers.ipynb
  examples/unstructured_profilers.ipynb
Labels: High Priority, Refactor

#322 Add new report structure to gh pages docs
  docs/source/index.rst
Labels: Documentation

#329 Fix typo in stats out
  docs/source/index.rst
Labels: Documentation

#334 Update github pages for consistency
  docs/source/index.rst
Labels: Documentation

#335 V0.6.0
  dataprofiler/version.py
Labels: Documentation, High Priority

#326 Refactor StringIO/ByteIO changes made to is_match functions
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/filepath_or_buffer.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/tests/data_readers/test_avro_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/data_readers/test_filepath_or_buffer.py
  dataprofiler/tests/data_readers/test_json_data.py
  dataprofiler/tests/data_readers/test_parquet_data.py
Labels: High Priority, Refactor

#298 Standardize structured throughput testing
  dataprofiler/tests/speed_tests/data/time_structured_profiler.csv
  dataprofiler/tests/speed_tests/structured_throughput_testing.py
  dataprofiler/tests/speed_tests/throughput-test-guidelines.md
Labels: Documentation, Low Priority, New Feature

#343 Allow user to have non-str in pandas passed to Labeler
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
Labels: Bug, High Priority

#344 Abstract timeit function to allow other classes in the library to utilize the timeit property
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_float_column_profile.py
Labels: High Priority, Refactor

#337 Move profile to numeric stats mixin
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
Labels: Low Priority, Refactor

#340 Add text size to unstructured profiler
  README.md
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/test_utils.py
Labels: Medium Priority, New Feature

#339 Unstructured Text Diff
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_unstructured_text_profile.py
  dataprofiler/tests/profilers/test_utils.py
Labels: High Priority, New Feature

#345 Gh pages update: Add memory size
  docs/source/index.rst
Labels: Documentation

#342 Add correlation update with NaNs - Impute with mean
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor

#346 Add timing of profiles to StructuredProfiler and UnstructuredProfiler
  README.md
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/utils.py
Labels: High Priority, New Feature

#347 Allow user to specify null values for profiled dataset
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_class_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Medium Priority, New Feature

#351 Buffer issue and cleanup tests pep8
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/data_readers/test_parquet_data.py
Labels: Bug, High Priority

#356 Update to Structured throughput changes for new timing in StructuredProfiler
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/speed_tests/structured_throughput_testing.py
Labels: Low Priority, Refactor

#360 Allow internal data function calls directly from our data class
  dataprofiler/data_readers/base_data.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/tests/data_readers/test_base_data.py
Labels: Low Priority, New Feature

#362 Removed Unnecessary README lines and updated requirements
  README.md
  requirements.txt
Labels: Documentation, Low Priority, security fix

#358 Top Profiler Structured Diff
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/test_utils.py
Labels: High Priority, New Feature

#359 Top Level Unstructured Diff
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#363 List now maintains same visual data representation
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug

#366 Add chi-squared test to categorical diff
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
Labels: High Priority, New Feature

#369 Add scipy to requirements
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  requirements-ml.txt
  requirements.txt
Labels: High Priority, Refactor

#370 Update version to 0.7.0
  dataprofiler/version.py
Labels: High Priority, New Feature

#372 Adding Diff to GH-Pages
  docs/source/profiler.rst
Labels: Documentation
