Repository capitalone/DataProfiler, pull requests merged in 2021-11, with the labels that each got.

#426 Bug fix to handle final word in word level argmax
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_data_processing.py
Labels: Bug, Medium Priority

#428 fix: numpy removing trailing nulls from strings
  dataprofiler/labelers/data_processing.py
Labels: Bug, High Priority

#429 Add test for numpy removing trailing nulls from strings and Increment Version 0.7.4
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/version.py
Labels: Bug, Documentation, High Priority
