Repository capitalone/DataProfiler, pull requests merged in 2021-06, with the labels that each got.

#248 Fixes mock in test to use proper tf.keras
  dataprofiler/tests/labelers/test_data_labelers.py
  requirements-ml.txt
Labels: Bug, High Priority

#257 Fixes save bug and add tests
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#255 Adding __add__ to the unstructured data labeler profile
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_unstructured_labeler_profile.py
Labels: Bug, High Priority

#252 Updating profile example to have unstructured
  examples/add_new_model_to_data_labeler.ipynb
  examples/data_readers.ipynb
  examples/intro_data_profiler.ipynb
  examples/labeler.ipynb
  examples/structured_profilers.ipynb
  examples/unstructured_profilers.ipynb
Labels: Documentation

#258 Update version to v0.5.1
  dataprofiler/version.py
Labels: Documentation, High Priority

#260 Option Equality
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_base_inspector_options.py
  dataprofiler/tests/profilers/profiler_options/test_base_option.py
  dataprofiler/tests/profilers/profiler_options/test_boolean_option.py
  dataprofiler/tests/profilers/profiler_options/test_categorical_options.py
  dataprofiler/tests/profilers/profiler_options/test_datalabeler_options.py
  dataprofiler/tests/profilers/profiler_options/test_datetime_options.py
  dataprofiler/tests/profilers/profiler_options/test_float_options.py
  dataprofiler/tests/profilers/profiler_options/test_histogram_option.py
  dataprofiler/tests/profilers/profiler_options/test_int_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_order_options.py
  dataprofiler/tests/profilers/profiler_options/test_precision_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/profiler_options/test_text_options.py
  dataprofiler/tests/profilers/profiler_options/test_unstructured_options.py
  dataprofiler/tests/profilers/profiler_options/test_unstructured_text_profile_options.py
Labels: Medium Priority, New Feature

#268 Adding Contributions to Repo
  .github/CONTRIBUTING.md
Labels: Documentation

#267 Add Num zeros and Num negatives feature
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_text_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: High Priority, New Feature

#270 Fixes propagation error in options when setting generic values
  dataprofiler/data_readers/json_data.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/profiler_options/test_boolean_option.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  requirements.txt
Labels: Bug, High Priority

#271 Added seed library variable
  dataprofiler/__init__.py
  dataprofiler/profilers/utils.py
  dataprofiler/settings.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/utils.py
  dataprofiler/tests/test_data_profiler.py
Labels: High Priority, New Feature

#269 Add option for turning on/off bias correction
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
Labels: Medium Priority, New Feature

#277 Numerical Stats Differences
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_utils.py
Labels: High Priority, New Feature

#283 Update to v0.5.2 with new stats
  dataprofiler/version.py
Labels: High Priority, New Feature

#290 Hotfix: remove unused import causing profiler error
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/version.py
Labels: Bug, High Priority
