Repository capitalone/DataProfiler, pull requests merged in 2021-04, with the labels that each got.

#122 Added multiprocessing of column profiles (40% runtime reduction)
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_profiler_options.py
Labels: Medium Priority, New Feature, Refactor

#125 add length to data reader class (no tests for text data)
  README.md
  dataprofiler/data_readers/base_data.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/data_readers/test_avro_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/data_readers/test_json_data.py
  dataprofiler/tests/data_readers/test_parquet_data.py
Labels: Low Priority, New Feature

#130 Shuffle sampling indices once, when possible (reduced runtime by 15%)
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
Labels: Bug, High Priority

#131 vectorized precision function
  dataprofiler/profilers/float_column_profile.py
Labels: Medium Priority, Refactor

#127 Refactor to ensure multiprocessing happens on profile updates as well
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
Labels: Bug, Low Priority, Refactor

#132 Move multiprocessing pool to profiler level
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/profile_builder.py
Labels: Medium Priority, Refactor

#134 Fix histogram options (reduced runtime 30%)
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_histogram_option.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
  doc/DATA_LOADING.md
Labels: Bug, High Priority

#135 Improved unique set & vocab methods (reduced runtime 5-10%)
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: Medium Priority, Refactor

#137 updated documentation for multiprocessing
  README.md
Labels: Documentation, Low Priority

#138 Fixes a bug in tensorflow import test when tests are ran sequentially
  dataprofiler/tests/test_data_profiler.py
Labels: Bug

#115 Add tests for Structured and Profiler Options
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/__init__.py
  dataprofiler/tests/profilers/profiler_options/abstract_test_options.py
  dataprofiler/tests/profilers/profiler_options/test_base_column_options.py
  dataprofiler/tests/profilers/profiler_options/test_base_option.py
  dataprofiler/tests/profilers/profiler_options/test_boolean_option.py
  dataprofiler/tests/profilers/profiler_options/test_categorical_options.py
  dataprofiler/tests/profilers/profiler_options/test_datalabeler_options.py
  dataprofiler/tests/profilers/profiler_options/test_datetime_options.py
  dataprofiler/tests/profilers/profiler_options/test_float_options.py
  dataprofiler/tests/profilers/profiler_options/test_int_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_order_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_class_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/profiler_options/test_text_options.py
  dataprofiler/tests/profilers/test_histogram_option.py
Labels: Low Priority, Refactor

#141 appropriately copy options in profile merges
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/profile_builder.py
Labels: Medium Priority, Refactor

#142 Continued fixes for option passing on merge of profiles
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/profile_builder.py
Labels: Medium Priority, Refactor

#149 Fix bug in merging DateTimeColumn profiles
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
Labels: Bug, High Priority

#150 Fix multiprocessing for osx and slight speed improvements
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/version.py
Labels: Medium Priority, Refactor

#155 Allow user to set the histogram bin count (moving towards speeding up histograms)
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/abstract_test_options.py
  dataprofiler/tests/profilers/profiler_options/test_histogram_option.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_histogram_option.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: Medium Priority, New Feature

#153 Expanded precision report (and 40% reduced runtime on numeric columns)
  README.md
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_precision_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#157 Mitigated type bug in json output & runtime improvements
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority, Refactor

#152 add example: add new model to data labeler
  examples/add_new_model_to_data_labeler.ipynb
Labels: Documentation, Low Priority

#147 Intuitive Json Detection
  README.md
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/tests/data/json/complex_nested.json
  dataprofiler/tests/data/json/dual_payloads.json
  dataprofiler/tests/data/json/hits.json
  dataprofiler/tests/data/json/math.json
  dataprofiler/tests/data/json/simple.json
  dataprofiler/tests/data_readers/test_json_data.py
Labels: High Priority, New Feature, Refactor

#159 Improved null finder and Multiprocessing - Oh my! (35% runtime reduction)
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/labelers/test_character_level_cnn_model.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature, Refactor

#144 update get_percentiles to take in an array
  README.md
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: High Priority, Refactor

#172 Ensure sample size limited for large data
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#173 Add safety when spinning up pool
  README.md
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  requirements.txt
Labels: Bug, Medium Priority, Refactor

#170 Adding Unstructured Text Profiler
  .github/workflows/test-python-package.yml
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/tests/profilers/test_unstructured_text_profile.py
Labels: Medium Priority, New Feature

#166 Fix Null Row calculations
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#184 fixes the len data error if data sent in is
  dataprofiler/profilers/profile_builder.py
Labels: Bug, High Priority

#185 null count and row duplicate update bug fixes
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#183 add UnstructuredCompiler and tests
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_datatype_column_profiler.py
  dataprofiler/tests/profilers/test_stats_column_profiler.py
  dataprofiler/tests/profilers/test_unstructured_labeler_profile.py
Labels: High Priority, New Feature

#154 Save and Load from Disk
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#192 Fixes csv bug and formatting / add test
  dataprofiler/data_readers/csv_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: Bug, High Priority

#193 Counts null-rows appropriately
  dataprofiler/data_readers/data_utils.py
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: Bug, High Priority

#201 CSVData shouldn't combine all records -> single sample, default 1
  dataprofiler/data_readers/csv_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: High Priority, New Feature

#202 Allows user to reload data that already was loaded if no file path specified originally
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/base_data.py
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/data_readers/parquet_data.py
  dataprofiler/data_readers/text_data.py
Labels: Bug, High Priority

#191 Updated notebook
  examples/intro_data_profiler.ipynb
Labels: Documentation, Low Priority

#199 Handling index overlap when merging and updating profiles
  README.md
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#198 Add Profiler python notebook example
  README.md
  examples/profilers.ipynb
Labels: Documentation, Low Priority

#203 Example: Intro to Data Readers
  dataprofiler/tests/data_readers/test_avro_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
  dataprofiler/tests/data_readers/test_json_data.py
  dataprofiler/tests/data_readers/test_parquet_data.py
  dataprofiler/tests/data_readers/test_text_data.py
  examples/data_readers.ipynb
Labels: High Priority, New Feature
