Repository capitalone/DataProfiler, pull requests merged in 2021-05, with the labels that each got.

#211 Add unstructured profiler
  dataprofiler/labelers/data_processing.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/profiler_options/test_precision_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#215 add save / load to unstructured profiler
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#220 Fix for avro reader test files format, limit TF version till fix.
  dataprofiler/tests/data/avro/deflate_compressed_intentionally_mislabeled_file.csv
  dataprofiler/tests/data/avro/snappy_compressed_intentionally_mislabeled_file.csv
  dataprofiler/tests/data/avro/users.avro
  requirements-ml.txt
Labels: Bug, High Priority

#222 Update with main branch to include recent updates / fixes.
  dataprofiler/profilers/histogram_utils.py
  dataprofiler/tests/data/avro/deflate_compressed_intentionally_mislabeled_file.csv
  dataprofiler/tests/data/avro/snappy_compressed_intentionally_mislabeled_file.csv
  dataprofiler/tests/data/avro/users.avro
  requirements-ml.txt
Labels: High Priority

#218 Modify ProfilerOptions.set to require specification when setting certain options
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
Labels: Medium Priority

#225 Fixes TF error when padding with numpy 1.20.3
  dataprofiler/labelers/character_level_cnn_model.py
Labels: Bug, High Priority

#226 Remove PAD from structured labeling output
  dataprofiler/labelers/data_processing.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
Labels: Bug, High Priority

#227 Add BaseProfiler abstraction template
  dataprofiler/profilers/profile_builder.py
Labels: High Priority, Refactor

#232 Refactor / merge get_sample_size for BaseProfiler
  dataprofiler/profilers/profile_builder.py
Labels: High Priority, Refactor

#233 Refactor by abstracting __init__ for BaseProfiler
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor

#236 Add Unstructured Profiler to main
  dataprofiler/__init__.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/profilers/profiler_options/test_base_inspector_options.py
  dataprofiler/tests/profilers/profiler_options/test_categorical_options.py
  dataprofiler/tests/profilers/profiler_options/test_datalabeler_options.py
  dataprofiler/tests/profilers/profiler_options/test_datetime_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_order_options.py
  dataprofiler/tests/profilers/profiler_options/test_precision_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/profiler_options/test_unstructured_options.py
  dataprofiler/tests/profilers/profiler_options/test_unstructured_text_profile_options.py
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_datatype_column_profiler.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/test_stats_column_profiler.py
  dataprofiler/tests/profilers/test_unstructured_labeler_profile.py
  dataprofiler/tests/profilers/test_unstructured_text_profile.py
  dataprofiler/version.py
  examples/add_new_model_to_data_labeler.ipynb
  examples/intro_data_profiler.ipynb
  examples/labeler.ipynb
  examples/profilers.ipynb
Labels: High Priority, New Feature

#237 Abstract __add__ for Profilers
  dataprofiler/profilers/profile_builder.py
Labels: High Priority, Refactor

#240 Normalize update_profile_from_chunk function signature for Profilers
  dataprofiler/profilers/profile_builder.py
Labels: High Priority, Refactor

#242 Refactor save / load for profilers via BaseProfiler abstraction
  dataprofiler/profilers/profile_builder.py
Labels: High Priority, Refactor

#244 Abstract profiler property for the profilers
  dataprofiler/profilers/profile_builder.py
Labels: High Priority, Refactor

#245 Bug fix for dicts being passed to structured
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#247 Updates to intuitive profiler choice
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor
