Repository capitalone/DataProfiler, pull requests merged in 2022-09, with the labels that each got.

#622 Notebook Examples for DP + GE: expect_column_value_confidence
  .gitignore
  dataprofiler/tests/data/csv/ds_salaries.csv
  examples/great_expecations/README.md
  examples/great_expecations/ge_expect_column_value_confidence_for_data_label.ipynb
Labels: Documentation

#623 Notebook Examples for DP + GE: expect_column_values_vs_profile
  examples/great_expecations/README.md
  examples/great_expecations/ge_expect_column_value_confidence_for_data_label.ipynb
  examples/great_expecations/ge_expect_column_values_vs_profile_min.ipynb
Labels: Documentation, New Feature

#626 New Data Labeler: ColumnNameModel Build
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/column_name_model.py
  dataprofiler/tests/labelers/test_column_name_model.py
  requirements-ml.txt
Labels: New Feature

#627 Quick Add: `require_module` in `ColumnNameModel` test
  dataprofiler/labelers/column_name_model.py
  dataprofiler/labelers/utils.py
  dataprofiler/tests/labelers/test_column_name_model.py
Labels: New Feature

#628 Graph Profiler: save() and load() Functionality
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/tests/profilers/test_graph_profiler.py
  examples/great_expecations/README.md
  examples/great_expecations/ge_expect_column_value_confidence_for_data_label.ipynb
  examples/great_expecations/ge_expect_column_values_vs_profile_min.ipynb
  examples/great_expecations/ge_expect_profile_numeric_columns_diff_in_range.ipynb
  examples/great_expecations/ge_expect_profile_numeric_columns_percent_diff_in_range.ipynb
Labels: High Priority

#632 README unti testing docs
  README.md
Labels: Bug, Documentation

#634 Fix for issue #605
  dataprofiler/validators/base_validators.py
Labels: Work In Progress, Medium Priority, New Feature, static_typing

#638 Preset option in ProfileOptions
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_presets.py
Labels: High Priority, New Feature

#629 Post Processor for ColumnNameModel
  dataprofiler/labelers/column_name_model.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_column_name_model.py
  dataprofiler/tests/labelers/test_data_processing.py
Labels: High Priority, New Feature

#635 ColumnNameLabeler Setup
  dataprofiler/labelers/column_name_model.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_column_name_model.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/tests/labelers/test_integration_column_name_data_labeler.py
  resources/labelers/column_name_labeler/data_labeler_parameters.json
  resources/labelers/column_name_labeler/label_mapping.json
  resources/labelers/column_name_labeler/model_parameters.json
  resources/labelers/column_name_labeler/postprocessor_parameters.json
  resources/labelers/column_name_labeler/preprocessor_parameters.json
Labels: High Priority, New Feature

#646 ColumnNameLabeler Notebook Example
  examples/column_name_labeler.ipynb
Labels: Documentation, High Priority, New Feature

#644 Static Typing profilers/profiler_options.py
  dataprofiler/profilers/profiler_options.py
Labels: static_typing

#649 DataProfiler: `graph_data_demo` update
  examples/graph_data_demo.ipynb
Labels: Documentation, High Priority

#653 DataProfiler: `structured_profilers` example fix
  examples/structured_profilers.ipynb
Labels: Bug, Documentation

#654 fix: remove extra commas
  .pre-commit-config.yaml
  examples/graph_data_demo.ipynb
Labels: Bug, Documentation

#655 fix: nb issues being valid
  examples/graph_data_demo.ipynb
Labels: Bug, High Priority

#630 Static Typing profilers/utils.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_utils.py
Labels: static_typing

#645 Static Typing for Base Column Primitive Type Profilers
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/text_column_profile.py
Labels: static_typing

#659 Added static typing to data_readers/structured_mixins.py
  dataprofiler/data_readers/structured_mixins.py
Labels: static_typing

#643 Static Typing profilers/profile_builder.py
  dataprofiler/profilers/profile_builder.py
Labels: static_typing

#648 Static Typing profilers/numerical_column_stats.py
  dataprofiler/profilers/numerical_column_stats.py
Labels: static_typing

#660 Static Typing profiler
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/unstructured_text_profile.py
Labels: static_typing

#661 Static Typing profilers/column profile
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/order_column_profile.py
Labels: static_typing

#657 Added static typing to data_readers/avro_data.py
  dataprofiler/data_readers/avro_data.py
Labels: static_typing

#663 Static typing for profilers
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/histogram_utils.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/profilers/utils.py
Labels: static_typing

#664 Add static typing to data labeler and abstract classes
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/data_labelers.py
Labels: static_typing

#667 Fixes bug with empty data for DataLabeler Col
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#669 Allow diff to set format options for prepare report
  dataprofiler/data_readers/structured_mixins.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/labelers/test_unstructured_data_labeler.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Medium Priority, New Feature

#668 Add static typing to labeler utils
  dataprofiler/labelers/classification_report_utils.py
  dataprofiler/labelers/labeler_utils.py
  dataprofiler/labelers/utils.py
Labels: static_typing

#670 Add logo readme
  README.md
Labels: Documentation

#671 Fixes 0 variance in a dataset
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
Labels: Bug, High Priority
