Repository capitalone/DataProfiler, pull requests merged in 2022-12, with the labels that each got.

#728 Updating the version to v0.8.4
  dataprofiler/version.py
Labels: Version Upgrade

#731 Replaces Merging dict func
  .gitignore
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
Labels: Bug

#732 Generate Docs for v0.8.4
  docs/0.8.4/doctrees/dataprofiler.profilers.utils.doctree
  docs/0.8.4/doctrees/environment.pickle
  docs/0.8.4/html/dataprofiler.profilers.utils.html
  docs/0.8.4/html/genindex.html
  docs/0.8.4/html/objects.inv
  docs/0.8.4/html/searchindex.js
Labels: Documentation

#735 loosening pin on typing-extensions
  requirements.txt
Labels: dependencies

#736 Rework Graph Test for mocking missing imports
  dataprofiler/tests/reports/test_graphs.py
Labels: Bug, Medium Priority

#739 Windows Install error - Path Resouces - Fixes #738
  setup.py
Labels: Bug

#740 removing six
  .pre-commit-config.yaml
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/test_text_column_profile.py
  requirements.txt
Labels: dependencies

#742 Update version to 0.8.5
  dataprofiler/version.py
Labels: Bug, Medium Priority, Refactor
