Repository capitalone/DataProfiler, pull requests merged in 2022-01, with the labels that each got.

#433 Update Codeowners
  CODEOWNERS
Labels: Medium Priority, Refactor

#436 Add @taylorfturner in codeowners
  CODEOWNERS
Labels: Documentation, High Priority

#437 Hot Fix: Fix Ignore Config Values
  dataprofiler/labelers/data_processing.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
Labels: High Priority

#435 Add is_pred_labels to struct labeler and increment version
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/version.py
Labels: High Priority, New Feature

#438 Fixes request missing for url data reading
  requirements.txt
Labels: Bug, High Priority
