Repository capitalone/DataProfiler, pull requests merged in 2022-11, with the labels that each got.

#688 Adding `PSI` to `diff` report
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: Medium Priority, New Feature

#705 Updated setup.cfg with check-manifest
  .pre-commit-config.yaml
  MANIFEST.in
  manifest.in
  requirements-dev.txt
  setup.cfg
Labels: High Priority, New Feature, dependencies

#704 Add profiler option for column level invalid values
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Medium Priority, New Feature

#707 PSI `diff()` bug
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: Bug, Work In Progress, High Priority

#706 Fix bug with null replication metrics when row is all null
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#709 Add PSI documentation in README.md
  README.md
Labels: Documentation, Low Priority

#703 Updated setup.cfg mypy flags and resolved related errors.
  .pre-commit-config.yaml
  MANIFEST.in
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/data_readers/structured_mixins.py
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/labelers/labeler_utils.py
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/utils.py
  dataprofiler/validators/base_validators.py
  setup.cfg
Labels: High Priority, static_typing

#710 Updating the version to v0.8.3
  dataprofiler/version.py
Labels: Work In Progress, Version Upgrade

#712 PSI fixing unit tests
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: Bug, High Priority

#714 PSI blurb in Docs for 0.8.3
  docs/source/profiler.rst
Labels: Documentation

#725 Fix numpy version and drop python 3.7 in checks
  .github/workflows/test-python-package.yml
  requirements.txt
  setup.py
Labels: Bug, security vulnerability, Medium Priority, dependencies

#726 Great Expectations Examples Fix
  .gitignore
  examples/great_expectations/README.md
  examples/great_expectations/ge_expect_column_value_confidence_for_data_label.ipynb
  examples/great_expectations/ge_expect_column_values_vs_profile_min.ipynb
  examples/great_expectations/ge_expect_profile_numeric_columns_diff_in_range.ipynb
  examples/great_expectations/ge_expect_profile_numeric_columns_percent_diff_in_range.ipynb
Labels: Documentation, Refactor
