Repository capitalone/DataProfiler, pull requests merged in 2022-08, with the labels that each got.

#577 Primitive Historical Profiler Implementation
  .github/workflows/test-python-package.yml
  dataprofiler/__init__.py
  dataprofiler/profilers/WIP_historical_profiler_advanced.py
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/historical_profiler.py
  dataprofiler/tests/data/csv/ny_climate.csv
  dataprofiler/tests/profilers/test_historical_profiler.py
  examples/WIP_historical_profiler_advanced.ipynb
  examples/historical_profile_great_expectations_proof_of_concept.ipynb
  examples/historical_profiler.ipynb
Labels: High Priority, New Feature

#579 Add property array to continuous distribution profile in GraphProfiler/ Integer Node ID identified as Integer in GraphData
  dataprofiler/data_readers/graph_data.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/tests/data_readers/test_csv_graph_data.py
  dataprofiler/tests/profilers/test_graph_profiler.py
Labels: High Priority, New Feature

#581 Implement GraphData/GraphProfiler into DataProfiler Pipeline
  dataprofiler/__init__.py
  dataprofiler/data_readers/data.py
  dataprofiler/data_readers/graph_data.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/data/csv/graph_data_csv_identify.csv
  dataprofiler/tests/data_readers/test_csv_graph_data.py
  dataprofiler/tests/profilers/test_graph_profiler.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#584 HOT FIX: example notebook update
  examples/merge_profile_list.ipynb
Labels: Documentation

#585 Updating the Version to v0.8.0
  dataprofiler/version.py
Labels: High Priority, dependencies

#586 Hot fix/notebook
  examples/merge_profile_list.ipynb
Labels: Bug, Documentation

#588 HOT FIX: black formatting issue
  dataprofiler/tests/data_readers/test_csv_graph_data.py
  dataprofiler/tests/profilers/test_graph_profiler.py
Labels: Bug, Documentation, High Priority

#592 fix: missing null_rep matrix info
  docs/source/profiler.rst
Labels: Documentation, Medium Priority

#594 Add example notebook for graph data input
  examples/graph_data_demo.ipynb
Labels: Documentation, High Priority

#597 Update ReadMe to include Graph Profiler
  README.md
Labels: Documentation, High Priority

#600 Graph Pipeline Demo notebook header fix
  examples/graph_data_demo.ipynb
Labels: Bug, Documentation, High Priority

#599 Add Graph Github Pages
  docs/source/data_readers.rst
  docs/source/examples.rst
  docs/source/graph_data_demo.nblink
  docs/source/index.rst
  docs/source/profiler.rst
Labels: Documentation, High Priority, New Feature

#602 Fixes GraphProfiler loading directly with class
  dataprofiler/data_readers/graph_data.py
  dataprofiler/tests/data_readers/test_csv_graph_data.py
Labels: Bug, High Priority

#603 Graph loading bug
  README.md
  dataprofiler/data_readers/graph_data.py
  dataprofiler/tests/data_readers/test_csv_graph_data.py
Labels: Bug, High Priority

#611 Hot Fix: Typo in Graph Docstring
  dataprofiler/profilers/graph_profiler.py
Labels: Bug, Documentation

#612 fixes profile_schema bug for unnamed columns
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#613 Include compact in fix for profile schema serialization
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#615 Updating the version to v0.7.11
  dataprofiler/version.py
Labels: release

#617 formatting issue for 0.7.11 docs
  examples/graph_data_demo.ipynb
Labels: Bug, Documentation, High Priority

#614 Update TF / numpy reqs, drop py3.6
  .github/workflows/test-python-package.yml
  requirements-dev.txt
  requirements-ml.txt
  requirements.txt
  resources/labelers/structured_model/keras_metadata.pb
  resources/labelers/structured_model/saved_model.pb
  resources/labelers/structured_model/variables/variables.data-00000-of-00001
  resources/labelers/structured_model/variables/variables.index
  resources/labelers/unstructured_model/keras_metadata.pb
  resources/labelers/unstructured_model/saved_model.pb
  resources/labelers/unstructured_model/variables/variables.data-00000-of-00001
  resources/labelers/unstructured_model/variables/variables.index
  setup.py
Labels: Medium Priority, Refactor

#619 Update documentation README for gh-pages branch
  README.md
Labels: Documentation, Low Priority
