Repository capitalone/DataProfiler, pull requests merged in 2022-07, with the labels that each got.

#517 Add a class to differentiate between Tabular and Graph CSV files
  dataprofiler/data_readers/graph_data.py
  dataprofiler/tests/data/csv/graph-data-input-json.json
  dataprofiler/tests/data/csv/graph-differentiator-input-negative.csv
  dataprofiler/tests/data/csv/graph-differentiator-input-positive.csv
  dataprofiler/tests/data/csv/graph-differentiator-input-standard-positive.csv
  dataprofiler/tests/data_readers/test_csv_graph_data.py
  requirements.txt
Labels: Medium Priority, New Feature

#536 HOT FIX: update README and remove isort.cfg
  .isort.cfg
  README.md
Labels: Bug, Documentation

#538 HOT FIX: resolving black and isort
  dataprofiler/data_readers/graph_data.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/labelers/labeler_utils.py
  dataprofiler/tests/data_readers/test_csv_graph_data.py
  dataprofiler/tests/labelers/test_labeler_utils.py
Labels: Bug

#547 Hot Fix: Resolving Version in Pre-Commit File
  .pre-commit-config.yaml
  README.md
Labels: Bug, High Priority

#550 Reformatted dataprofiler/dp_logging.py using flake8; changed first docstring in float, text, and order column profiler modules.
  dataprofiler/dp_logging.py
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/text_column_profile.py
Labels: Work In Progress

#552 [UTILs] Adding top-level function for distributed merging of profiles
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_utils.py
Labels: Bug, High Priority

#546 Graph Profiler class to create a profile of an input graph
  dataprofiler/data_readers/graph_data.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/tests/data/csv/graph-differentiator-input-standard-positive.csv
  dataprofiler/tests/profilers/test_graph_profiler.py
Labels: Work In Progress

#559 Adding `Example` for `merge_profile_list`
  examples/merge_profile_list_example.ipynb
Labels: Documentation, High Priority

#569 Reformatted batch 4 (see comment) using flake8.
  .pre-commit-config.yaml
  dataprofiler/__init__.py
  dataprofiler/data_readers/base_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/labelers/classification_report_utils.py
  dataprofiler/labelers/regex_model.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/validators/__init__.py
  setup.py
Labels: High Priority

#570 Tox
  manifest.in
  tox.ini
Labels: High Priority, New Feature
