Repository capitalone/DataProfiler, pull requests merged in 2022-06, with the labels that each got.

#491 Numeric Stats Mixin: `pop` disabled elements from profile report
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
Labels: New Feature

#499 PR for column compiler reports
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
Labels: High Priority

#496 Profile Builder: add `report` for `remove_disable_flag` at the top level
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#500 Added the statistic descriptions to GitHub pages
  LICENSE
  docs/source/profiler.rst
Labels: Documentation
