Repository capitalone/DataProfiler, pull requests merged in 2022-10, with the labels that each got.

#675 Updating the version to v0.8.1
  dataprofiler/version.py
Labels: Version Upgrade

#676 Replace dict constructor with dict comprehension
  dataprofiler/profilers/data_labeler_column_profile.py
Labels: Refactor

#680 Quick Fix
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/char_load_tf_model.py
  dataprofiler/labelers/character_level_cnn_model.py
  dataprofiler/tests/labelers/test_integration_struct_data_labeler.py
  dataprofiler/tests/labelers/test_integration_unstructured_data_labeler.py
Labels: static_typing

#673 Add static typing to labelers/data_processing.py
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_data_processing.py
Labels: static_typing

#666 Added static typing to data_readers/base_data.py and data_readers/json_data.py
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/base_data.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/data_readers/structured_mixins.py
Labels: static_typing

#682 Added static typing to data.py and filepath_or_buffer.py
  dataprofiler/data_readers/data.py
  dataprofiler/data_readers/filepath_or_buffer.py
Labels: static_typing

#683 Move contribute info to CONTRIBUTING.md
  .github/CONTRIBUTING.md
  README.md
Labels: Documentation

#686 Fix `matplotlib` version requirements param
  requirements-reports.txt
Labels: Bug

#690 Fix typos, remove (unintended?) indentation
  .github/CONTRIBUTING.md
  examples/intro_data_profiler.ipynb
  examples/structured_profilers.ipynb
Labels: Documentation, Low Priority

#691 fix JSON bug with data reading
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/filepath_or_buffer.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/tests/data/json/simple-list.json
  dataprofiler/tests/data_readers/test_json_data.py
Labels: Bug, High Priority

#681 Adding the types of parameters and returns of functions
  dataprofiler/profilers/profile_builder.py
  dataprofiler/reports/graphs.py
  dataprofiler/reports/utils.py
Labels: High Priority, static_typing

#687 Update ghworkflow actions to use pre-commit
  .github/workflows/test-python-package.yml
  dataprofiler/data_readers/data.py
  dataprofiler/labelers/base_model.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/reports/graphs.py
Labels: Medium Priority, New Feature

#677 Added static typing to *_data classes in data_readers
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/base_data.py
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/graph_data.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/data_readers/parquet_data.py
  dataprofiler/data_readers/text_data.py
  dataprofiler/tests/data_readers/test_base_data.py
Labels: High Priority, static_typing

#662 added static typing to data_utils.py
  dataprofiler/_typing.py
  dataprofiler/data_readers/data_utils.py
Labels: High Priority, static_typing

#694 Updating the version to v0.8.2
  dataprofiler/version.py
Labels: Work In Progress, Version Upgrade

#698 Fix req missing for typing_extensions
  dataprofiler/version.py
  requirements.txt
Labels: Bug, High Priority

#701 Pre-Commit: Default `setup.cfg` flags
  setup.cfg
Labels: High Priority, configuration error

#699 Add Makefile to auto setup repo for developers
  .github/CONTRIBUTING.md
  Makefile
Labels: Documentation, Medium Priority

#697 Quick Fix: Oxford Comma in README
  README.md
Labels: Bug, Documentation, Low Priority
