Repository capitalone/DataProfiler, pull requests merged in 2023-07, with the labels that each got.

#952 Fix/f1 score path fix import
  examples/add_new_model_to_data_labeler.ipynb
Labels: Documentation

#960 Hot Fix: `.astype("bool")`
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/version.py
Labels: Bug, Version Upgrade

#963 Add roadmap
  docs/source/index.rst
  docs/source/roadmap.rst
Labels: Documentation

#964 None-check labels dependants
  dataprofiler/labelers/data_processing.py
Labels: static_typing

#973 hotfix[0.10.2]: cat vs float bug
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/version.py
Labels: Bug, High Priority, Version Upgrade
