Repository capitalone/DataProfiler, pull requests merged in 2023-05, with the labels that each got.

#805 Specify __init__ calls in data readers reload() methods
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/json_data.py
  dataprofiler/data_readers/parquet_data.py
  dataprofiler/data_readers/text_data.py
Labels: static_typing

#810 implementation of setting stop conds via options for cat column profiler
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
Labels: Bug

#816 Fixes categorical bug when stop condition is met
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
Labels: Bug

#817 hotfix for more conservatitive stop condition in categorical columns
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
Labels: Bug

#822 Coverage Fix to Main Branch
  .github/workflows/test-python-package.yml
Labels: High Priority

#823 Coverage Fix Memory Optimization Feature Branch
  .github/workflows/test-python-package.yml
Labels: High Priority

#815 Fix for histogram merging
  dataprofiler/profilers/histogram_utils.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_histogram_utils.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
Labels: Bug, High Priority

#819 Fix override errors
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/text_column_profile.py
  setup.cfg
Labels: static_typing

#827 Added option to remove calculations for updating row statistics
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, New Feature

#828 added new options to docs
  docs/source/profiler.rst
Labels: Work In Progress

#837 added missing options to docs
  docs/source/profiler.rst
Labels: Documentation

#836 Docstring fix typos `bias` --> `bias_correction`
  dataprofiler/profilers/profiler_options.py
Labels: Documentation

#832 Memory Optimization to `main`
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/histogram_utils.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/profiler_options/test_categorical_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_histogram_utils.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/space_time_analysis/dataset_generation.py
  dataprofiler/tests/space_time_analysis/structured_space_time_analysis.py
  dataprofiler/tests/space_time_analysis/throughput-test-guidelines.md
Labels: High Priority, Refactor

#833 Github pages memory optimization
  docs/source/profiler.rst
Labels: Documentation

#825 Sampling ratio option
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
Labels: New Feature

#843 Fix argument types in doc comments
  dataprofiler/profilers/numerical_column_stats.py
Labels: Documentation

#848 Update version to 0.9.0
  dataprofiler/version.py
Labels: Version Upgrade

#844 Implemented decoding for numerical stats mixin and integer profiles
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: New Feature
