Repository capitalone/DataProfiler, pull requests merged in 2023-08, with the labels that each got.

#988 Fix Scipy Mend Issue
  requirements.txt
Labels: Bug, Mend: dependency security vulnerability, dependencies

#984 Automate multiprocess option
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_utils.py
  dataprofiler/tests/profilers/test_profiler_utils.py
Labels: High Priority, New Feature

#990 Staging: into dev feature/num-quantiles
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_float_options.py
  dataprofiler/tests/profilers/profiler_options/test_histogram_and_quantiles_option.py
  dataprofiler/tests/profilers/profiler_options/test_histogram_option.py
  dataprofiler/tests/profilers/profiler_options/test_int_options.py
  dataprofiler/tests/profilers/profiler_options/test_numerical_options.py
  dataprofiler/tests/profilers/profiler_options/test_text_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  requirements.txt
Labels: Mend: dependency security vulnerability, High Priority, New Feature

#997 Multiprocess automation feature into staging/dev.
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_utils.py
  dataprofiler/tests/profilers/test_profiler_utils.py
Labels: High Priority, New Feature

#1003 Fix hyperlink to profiler options
  docs/update_documentation.py
  profiler_options.html
Labels: Documentation

#1010 fixed snappy install issue on Mac
  docs/source/install.rst
Labels: Documentation

#1023 Add roadmap (back)
  docs/source/index.rst
  docs/source/roadmap.rst
Labels: Bug, Documentation
