Repository capitalone/DataProfiler, pull requests merged in 2023-04, with the labels that each got.

#784 Update for new Dask version in Validator test
  dataprofiler/validators/base_validators.py
Labels: High Priority

#787 Space analysis dataset sampling addition
  dataprofiler/tests/space_time_analysis/create_flamegraphs.sh
  dataprofiler/tests/space_time_analysis/structured_space_time_analysis.py
  dataprofiler/tests/space_time_analysis/throughput-test-guidelines.md
Labels: Refactor

#796 Remove unnecessary cast() in csv_data.py (1)
  dataprofiler/data_readers/csv_data.py
Labels: static_typing

#797 cleanup time space analysis code
  dataprofiler/tests/space_time_analysis/structured_space_time_analysis.py
  dataprofiler/tests/space_time_analysis/throughput-test-guidelines.md
Labels: Documentation

#798 Remove unnecessary cast() in csv_data.py (2)
  dataprofiler/data_readers/csv_data.py
Labels: static_typing

#803 Update feat mem
  dataprofiler/data_readers/csv_data.py
Labels: static_typing

#799 Update main with change in `memory-optimization`
  .github/workflows/test-python-package.yml
  dataprofiler/tests/space_time_analysis/structured_space_time_analysis.py
  dataprofiler/tests/space_time_analysis/throughput-test-guidelines.md
Labels: Bug

#800 Remove unnecessary cast() in data.py
  dataprofiler/data_readers/data.py
Labels: static_typing

#801 Remove unnecessary cast() in graph_data.py
  dataprofiler/data_readers/graph_data.py
Labels: static_typing

#786 Decode categorical
  dataprofiler/profilers/json_decoder.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: New Feature

#804 Fix CatgoricalColumn test
  dataprofiler/tests/profilers/test_categorical_column_profile.py
Labels: Refactor
