Repository capitalone/DataProfiler, pull requests merged in 2023-01, with the labels that each got.

#746 Removes futures from required libs
  dataprofiler/data_readers/text_data.py
  dataprofiler/labelers/base_model.py
  dataprofiler/labelers/classification_report_utils.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/labelers/labeler_utils.py
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/helpers/report_helpers.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/reports/graphs.py
  requirements.txt
  setup.cfg
Labels: Medium Priority, Refactor

#751 Update to version 0.8.7
  dataprofiler/version.py
Labels: Version Upgrade

#754 Bug: `requirements-ml` fix
  requirements-ml.txt
Labels: Bug, High Priority, dependencies

#755 Update to version 0.8.7.post1
  dataprofiler/version.py
Labels: Bug, dependencies, Version Upgrade

#760 [BUG] update isort version pin
  .pre-commit-config.yaml
Labels: dependencies
