Repository capitalone/DataProfiler, pull requests merged in 2023-09, with the labels that each got.

#1027 added psi calculation to categorical columns
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
Labels: Bug, High Priority

#1029 Staging/main/0.10.4
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/open_issue.md
  .github/workflows/publish-python-package.yml
  .github/workflows/test-python-package.yml
  dataprofiler/labelers/data_processing.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  examples/merge_profile_list.ipynb
Labels: Bug, High Priority

#1032 version bump
  dataprofiler/version.py
Labels: Version Upgrade

#1036 version bump (#1032)
  dataprofiler/version.py
Labels: Version Upgrade

#1039 Categorical PSI
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
Labels: Bug, High Priority

#1040 Categorical PSI
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/version.py
Labels: Bug, High Priority, Version Upgrade

#1043 Fix Codeowners List
  CODEOWNERS
Labels: Documentation
