Repository capitalone/DataProfiler, pull requests merged in 2023-10, with the labels that each got.

#1056 Rename references to degree of freedom from df to deg_of_free
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profiler_utils.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: good_first_issue

#1057 Update docs to reflect renamed output of deg_of_free
  docs/source/profiler.rst
Labels: Documentation

#1054 add_s3_connection_remote_loading_s3uri_feature
  .gitignore
  .pre-commit-config.yaml
  dataprofiler/data_readers/data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/tests/data_readers/test_data.py
  dataprofiler/tests/data_readers/test_data_utils.py
  dataprofiler/tests/data_readers/test_s3_helper.py
  requirements.txt
Labels: High Priority, New Feature
