Repository capitalone/DataProfiler, pull requests merged in 2023-06, with the labels that each got.

#852 hot fixes for encode and decode of numeric stats mixin and intcol pro…
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_options.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: New Feature

#845 Sampling ratio implement
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: New Feature

#854 Float column profiler encode decode
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: Work In Progress, New Feature

#841 StructuredOptions: `hhl_row_hashing`
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_hyper_log_log_options.py
  dataprofiler/tests/profilers/profiler_options/test_row_statistics_options.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/profiler_options/test_unique_count_options.py
Labels: Refactor

#857 Forking workflow directions CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Documentation

#862 Fixing diagram rendering in `CONTRIBUTING.md`
  .github/CONTRIBUTING.md
Labels: Bug, Documentation

#861 Json decode date time column
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: New Feature

#864 Added decoding for encoding of ordered column profiles
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/tests/profilers/test_order_column_profile.py
Labels: New Feature

#842 StructuredProfiler: HLLRowHashing
  .pre-commit-config.yaml
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_hyper_log_log_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
  requirements.txt
Labels: New Feature

#867 New preset implementation and test
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_presets.py
Labels: New Feature

#869 Created encoder for the datalabelercolumn
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/json_encoder.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
Labels: New Feature

#878 fix: test bug due to bad mocks
  dataprofiler/tests/labelers/test_character_level_cnn_model.py
Labels: Bug

#873 Fixed documentation for `sampling_ratio` option
  docs/source/profiler.rst
Labels: Documentation

#882 updating docs for preset name
  docs/source/profiler.rst
Labels: Documentation

#871 RowStatisticsOptions: Implementing option
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: New Feature

#884 feat: add test and compiler serialization
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/json_encoder.py
  dataprofiler/tests/profilers/test_base_column_profilers.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
Labels: Medium Priority, New Feature

#885 Adds tests validating serialization with Primitive type for compiler
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_float_column_profile.py
Labels: Medium Priority, New Feature

#886 Adds deserialization for compilers and validates tests for Primitive; fixes numerical deserialization
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/utils.py
Labels: Bug, Medium Priority, New Feature

#888 ColumnDataLabelerCompiler: serialize / deserialize
  dataprofiler/profilers/__init__.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
Labels: New Feature

#897 feat: add dev to workfow for testing
  .github/workflows/test-python-package.yml
Labels: High Priority, security vulnerability

#826 Reservoir sampling
  dataprofiler/data_readers/csv_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/graph_data.py
  dataprofiler/tests/data_readers/test_csv_data.py
Labels: New Feature

#902 refactor: allow options to go through all
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
Labels: Medium Priority, Refactor

#901 StructuredColProfiler Encode / Decode
  dataprofiler/labelers/data_labelers.py
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/json_encoder.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/utils.py
Labels: New Feature

#904 fix: bug and add tests for structuredcolprofiler
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
  requirements.txt
Labels: Bug, High Priority, Refactor

#903 Stuctured profiler encode decode
  dataprofiler/labelers/data_labelers.py
  dataprofiler/profilers/__init__.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/json_encoder.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/test_profile_builder.py
  dataprofiler/tests/profilers/utils.py
Labels: High Priority, New Feature

#909 staging/dev/options
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_profiler_presets.py
  dataprofiler/tests/profilers/profiler_options/test_row_statistics_options.py
  dataprofiler/tests/profilers/test_profile_builder.py
  requirements.txt
Labels: New Feature

#907 UnstructuredProfiler: Added NoImplementationError
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/json_encoder.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor

#915 Added testing for values for test_json_decode_after_update
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#914 Refactoring Deprecating pck_resources
  dataprofiler/labelers/base_data_labeler.py
  dataprofiler/labelers/data_labelers.py
  dataprofiler/labelers/data_processing.py
  dataprofiler/tests/labelers/test_char_tf_load_model.py
  dataprofiler/tests/labelers/test_character_level_cnn_model.py
  dataprofiler/tests/labelers/test_column_name_model.py
  dataprofiler/tests/labelers/test_data_labelers.py
  dataprofiler/tests/labelers/test_data_processing.py
  dataprofiler/tests/labelers/test_integration_column_name_data_labeler.py
  dataprofiler/tests/labelers/test_integration_regex_data_labeler.py
  dataprofiler/tests/labelers/test_regex_model.py
  requirements.txt
Labels: Medium Priority, Refactor

#892 Cms for categorical
  .pre-commit-config.yaml
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/profilers/profiler_options/test_categorical_options.py
  dataprofiler/tests/profilers/test_categorical_column_profile.py
  requirements.txt
Labels: High Priority, New Feature, Refactor

#917 documentation update for cms specific options to category
  docs/source/profiler.rst
Labels: Documentation

#919 Documentation: Update for Reservoir Sampling
  docs/source/data_readers.rst
Labels: Documentation

#921 Documentation: feature/options branch docs updates
  .gitignore
  docs/source/profiler.rst
Labels: Documentation

#922 Documentation: Fix Req
  requirements.txt
Labels: Documentation, dependencies

#924 Reuse passed labeler
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/profilers/utils.py
  dataprofiler/tests/profilers/profiler_options/test_datalabeler_options.py
  dataprofiler/tests/profilers/test_column_profile_compilers.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, New Feature, Refactor

#911 plugins loading + preset plugin fetching implementation
  dataprofiler/__init__.py
  dataprofiler/plugins/__init__.py
  dataprofiler/plugins/decorators.py
  dataprofiler/profilers/profiler_options.py
  dataprofiler/tests/plugins/test_plugins.py
  requirements.txt
Labels: Medium Priority, New Feature

#923 BaseProfiler save() for json
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: New Feature

#927 refactor: use seed for sample for consistency
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: New Feature

#928 Docs: Profiler Serialization
  docs/source/profiler.rst
Labels: Documentation

#931 Top level hotfix: save / load `.lower()`
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug

#932 Profiler: `load_method` hotfix
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug

#933 fix: null_rep mat should calculate even if datetime
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#930 Notebook Example save/load Profile
  examples/data_profiler_demo.ipynb
Labels: Documentation

#936 Docs: Profiler Serialization Clean Up
  docs/source/profiler.rst
Labels: Documentation

#937 Merge `staging/dev-gh-pages/profile-serialization` into `dev-gh-pages`
  docs/source/profiler.rst
Labels: Documentation

#939 fix: order bug
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/tests/profilers/test_order_column_profile.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: Bug, High Priority

#942 Hotfix: fix post feature serialization merge
  dataprofiler/profilers/base_column_profilers.py
  dataprofiler/profilers/categorical_column_profile.py
  dataprofiler/profilers/column_profile_compilers.py
  dataprofiler/profilers/data_labeler_column_profile.py
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/json_decoder.py
  dataprofiler/profilers/order_column_profile.py
  dataprofiler/profilers/profile_builder.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/profiler_options/test_structured_options.py
  dataprofiler/tests/profilers/test_data_labeler_column_profile.py
  dataprofiler/tests/profilers/test_graph_profiler.py
  dataprofiler/tests/profilers/test_profile_builder.py
Labels: High Priority, Refactor

#947 Plugin testing
  dataprofiler/plugins/__init__.py
  dataprofiler/tests/plugins/test_plugins.py
Labels: New Feature
