Repository capitalone/DataProfiler, pull requests merged in 2024-03, with the labels that each got.

#1105 Hot fix json bug
  dataprofiler/profilers/json_encoder.py
  dataprofiler/tests/labelers/test_labeler_utils.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
Labels: Bug

#1106 Staging into `main` from `dev`
  README.md
  dataprofiler/profilers/json_encoder.py
  dataprofiler/tests/labelers/test_labeler_utils.py
  dataprofiler/tests/profilers/test_datetime_column_profile.py
Labels: 0.10.9

#1103 Numeric updates
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/int_column_profile.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/profilers/text_column_profile.py
  dataprofiler/tests/profilers/test_float_column_profile.py
  dataprofiler/tests/profilers/test_int_column_profile.py
  dataprofiler/tests/profilers/test_numeric_stats_mixin_profile.py
  dataprofiler/tests/profilers/test_text_column_profile.py
Labels: polars

#1122 Revert prior PR into dev
  .pre-commit-config.yaml
  dataprofiler/__init__.py
  dataprofiler/tests/test_data_profiler.py
  requirements.txt
Labels: Bug
