Repository capitalone/DataProfiler, pull requests merged in 2024-04, with the labels that each got.

#1128 remove pandas
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/profilers/graph_profiler.py
  dataprofiler/tests/profilers/test_graph_profiler.py
Labels: polars

#1114 docs: update test link to latest version
  .github/CONTRIBUTING.md
Labels: Documentation

#1113 docs: add contributor notes on where to find documentation branches
  .github/CONTRIBUTING.md
Labels: Documentation

#1131 Update: `black` version
  requirements-dev.txt
Labels: dependencies

#1125 Bug fix for float precision calculation using categorical data with trailing 0s
  dataprofiler/profilers/float_column_profile.py
  dataprofiler/tests/profilers/test_float_column_profile.py
Labels: Bug

#1119 Polars feature updates
  dataprofiler/profilers/datetime_column_profile.py
  dataprofiler/profilers/profiler_utils.py
  dataprofiler/profilers/unstructured_labeler_profile.py
  dataprofiler/profilers/unstructured_text_profile.py
  dataprofiler/tests/profilers/test_unstructured_labeler_profile.py
  dataprofiler/tests/profilers/test_unstructured_text_profile.py
Labels: polars
