Repository capitalone/DataProfiler, pull requests merged in 2024-01, with the labels that each got.

#1072 Depedency: `matplotlib` version bump
  requirements-reports.txt
Labels: 0.10.8

#1071 Make _assimilate_histogram() not use self
  dataprofiler/profilers/numerical_column_stats.py
Labels: 0.10.8

#1082 Docs update to include option for `sample_nrows` for parquet files
  docs/source/data_readers.rst
Labels: Documentation, 0.10.8

#1081 Staging/main/0.10.8
  .github/workflows/publish-python-package.yml
  .github/workflows/test-python-package.yml
  dataprofiler/data_readers/avro_data.py
  dataprofiler/data_readers/data_utils.py
  dataprofiler/data_readers/parquet_data.py
  dataprofiler/profilers/numerical_column_stats.py
  dataprofiler/tests/data_readers/test_parquet_data.py
  dataprofiler/version.py
  requirements-reports.txt
Labels: Work In Progress, Version Upgrade, 0.10.8

#1087 add polars to requirements
  requirements.txt
Labels: dependencies
